[build]
    functions = "server"
    publish = "public"

[[redirects]]
    from = "/api-docs/*"
    to = "/.netlify/functions/app/:splat"
    status = 200

 [[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/app/:splat"
    status = 200   
   